### ISSUE TITLE
Carousel prioritization

### ISSUE THREAD

**Issue by siddadel** [RuralIndia/pari#162] opened 2015-01-23 21:13 UTC

**Comment by siddadel** [comment] 2015-01-23 21:16
1. Can we do something to force a priority on the landing page carousel?
that way, we won't have to arrive at what comes first (now, by trial and error, and mostly, purely by accident) 
If we could have - if it's not too difficult - something like in the categories list, a way to put in numbers 1 to 9, then it will be great! We could also, if need be, fix the number of items (or determine a maximum) for the carousel?

**Comment by jayakumarc** [comment] 2015-01-24 03:38
Duplicate of #155. Fixed and it's live.

**Closed by jayakumarc** 2015-01-24 03:38 UTC
